- hosts: all
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    kevin_elledge_pub_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDE8NStWRW6InR43i+XDxRGX5lG9IdnOzwkvT5TYswWZFaQwoDNJroj0XqcUP6vBG7NHQUsf94b/jejtJYyvWfm0rUFlD5rluuYuLda8swXhK0iSyYWdVBf+2LmTMiAaa5BXYLb5N/mknW79MJrgYCmK8kUKgIj+1fE75OpXYe0PL4GnDixohrwf+9otEOH+Zs/K0c2sNEsqTzZa9i2occURjFvAXXYBCOZV8IxiMcgx9RMhW/rW6n29ojFDLO2gs2XSZVbX0A38QtUfifVoQ2YRcXjmKp72yYlb2SFDJ4j35ZxGDSzM+NOPxLq8wPmeL4lnKsAk+lfgxedSgwpD341"
  tasks:
    - name: Add Docker repository key
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes

    - name: Install packages
      action: >
        apt name="{{ item }}" state=present update_cache=yes
      with_items:
        - docker-ce
        - tmux
        - zsh
        - git
        - virtualenvwrapper

    - name: Add 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: Add kevin.elledge to wheel group
      user:
        name: kevin.elledge
        groups: wheel,docker
        append: yes
        shell: '/usr/bin/zsh'
        createhome: yes
        state: present

    - name: Set up authorized keys for kevin.elledge
      authorized_key:
        user: kevin.elledge
        key: "{{kevin_elledge_pub_key}}"
