version: '3'

services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    image: jenkins:lts
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh.auth.sock
      - jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/tmp/docker.sock:rw
    environment:
      - 'DOCKER_HOST=unix:///tmp/docker.sock'
      - 'SSH_AUTH_SOCK=/ssh.auth.sock'
      - 'VIRTUAL_HOST=ci.kevinelledge.com'
      - 'VIRTUAL_PORT=8080'
      - 'HTTPS_METHOD=redirect'
      - 'LETSENCRYPT_HOST=ci.kevinelledge.com'
      - 'LETSENCRYPT_EMAIL=me@ci.kevinelledge.com'

volumes:
  jenkins_home:

networks:
  default:
    external:
      name: webproxy
